version: '3'
services:
  web:
    container_name: web
    image: nginx:alpine
    restart: always
    volumes:
      - ./:/app
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "14000:80"
    depends_on:
      - php
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker-config/php/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - redis
      - db
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker-config/node/Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
  redis:
    container_name: redis
    image: 'redis:latest'
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3307:3306'
